forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt', :git => "https://github.com/puppetlabs/puppetlabs-apt.git"
mod 'elastic/logstash', :git => "https://github.com/zsim0n/puppet-logstash.git"
mod 'elastic/elasticsearch', :git => "https://github.com/zsim0n/puppet-elasticsearch.git"
mod 'puppetlabs/java', :git => "https://github.com/puppetlabs/puppetlabs-java.git"
mod 'zsimon/nodejs', :git => "https://github.com/zsim0n/puppet-nodejs.git"
