forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs/apt', :git => "https://github.com/puppetlabs/puppetlabs-apt.git"
mod 'elastic/logstash', :git => "https://github.com/zsim0n/puppet-logstash.git"
mod 'elastic/elasticsearch', :git => "https://github.com/zsim0n/puppet-elasticsearch.git"
mod 'puppetlabs/java', :git => "https://github.com/puppetlabs/puppetlabs-java.git"
mod 'ispavailability/file_concat', :git => "https://github.com/electrical/puppet-lib-file_concat.git"

